---
- hosts: all
  become: true
  tasks:
    - name: update repository index and install nginx package
      package:
        name: nginx
        state: latest
      when: ansible_distribution in ["Ubuntu", "CentOS"]

    - name: start service nginx, if not started
      service:
        name: nginx
        state: started
