---
- hosts: all
  become: true
  tasks:
    - name: install nginx package and start nginx service
      package:
        name: nginx
        state: latest

    - name: starting the nginx service
      service:
        name: nginx
        enabled: yes
        state: started
      when: ansible_distribution in ["Ubuntu", "CentOS"]

    - name: copy site file to web root directory
      copy:
        src: files/
        dest: "{{ '/var/www/html/' if ansible_distribution == 'Ubuntu' else '/usr/share/nginx/html/' }}"
        owner: root
        group: root
        mode: 0644
