---

- hosts: ubuntu
  become: true
  tasks:
    - name: update repository index
      apt:
        update_cache: yes

    - name: install nginx package
      apt:
        name: nginx
        state: latest

    - name: start service nginx, if not started
      service:
        name: nginx
        state: started