---

- hosts: all
  become: true
  tasks:
    - name: update repository index
      apt:
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: install nginx package
      apt:
        name: nginx
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: start service nginx, if not started
      service:
        name: nginx
        state: started