---
- hosts: all
  become: true
  tasks:
    - name: update repository index and install nginx package
      tags: nginx
      package:
        name: nginx
        state: latest
      when: ansible_distribution in ["Ubuntu", "CentOS"]

    - name: start service nginx, if not started
      service:
        name: nginx
        state: started

    - name: copying the site file to web root directory
      copy:
        src: files/
        dest: /var/www/html/
        owner: root
        group: root
        mode: 0644
